import { servicesList } from "@/components/main/CoreServices";
import { APP } from "@/lib/App";

export const services = [
    "Dubai movers",
    "Best Mover Dubai",
    "Movers and Packers Dubai",
    "Moving Company Dubai",
    "Furniture Movers in Dubai",
    "Cheap Movers in Dubai",
    "Relocation Company in Dubai",
    "Same Day Furniture Removal",
    "Moving Company Dubai Prices",
    "Villa Movers in Dubai",
    "Cheap Moving Company Dubai",
    "Best Movers Packers Dubai",
    "Movers and Packers near me",
    "House shifting services",
    "UAE Mover Packers",
    "Mover and Packer in UAE",
    "Packers and Movers Near Me",
    "Residential Movers Near Me",
    "Movers and Packers Sharjah",
    "Furniture Movers in Dubai",
    "Cheap Movers and Packers in Dubai",
    "Best Moving Companies in Dubai",
    "Best Movers and Packers Dubai",
    "Local Movers in Dubai",
    "Office Movers in Dubai",
    "Movers and Packers Ajman",
    "Furniture Movers Abu Dhabi",
    "Cheap Movers and Packers in Abu Dhabi",
    "Best Moving Company in Abu Dhabi",
    "Professional Movers and Packers Dubai",
    "House Movers Abu Dhabi",
    "UAE Movers and Packers",
    "Best Movers in Abu Dhabi",
    "House Shifting Services Dubai",
    "Cheap Movers in Abu Dhabi",
    "Villa Movers and Packers in Dubai",
    "Villa Movers in Abu Dhabi",
    "Movers and Packers Al Ain",
    "Furniture Movers and Packers in Abu Dhabi",
    "Movers and Packers Dubai Marina",
    "Movers and Packers Al Quoz",
    "Office Movers and Packers in Dubai",
    "Best Movers and Packers in Abu Dhabi",
    "Office Movers in Abu Dhabi",
    "Movers and Packers in Dubai Marina",
    "Movers in Dubai Marina",
    "Packers and Movers Ajman",
    "Best Movers in Sharjah",
    "Abu Dhabi House Movers and Packers",
    "Expert Movers and Packers Dubai",
    "Movers and Packers Al Nahda Dubai",
    "Movers and Packers in Palm Jumeirah",
    "Movers and Packers in Mussafah",
    "Home Shifting Services in Abu Dhabi",
    "Best Movers and Packers in Sharjah",
    "Movers and Packers Bur Dubai",
    "Cheap and Best Movers and Packers in Dubai",
    "Movers in Al Nahda Dubai",
    "Movers and Packers Umm Al Quwain",
    "Movers and Packers Fujairah",
    "House Moving Companies in Abu Dhabi",
    "House Shifting Services in Sharjah",
    "Ajman Movers and Packers",
    "House Shifting Services in Abu Dhabi",
    "Office Movers in Ajman",
    "Best Furniture Movers in Dubai",
    "House Movers and Packers in Dubai",
    "Home Movers in Ajman",
    "Packers and Movers in Mussafah",
    "Home Shifting in Dubai",
    "Movers and Packers Sharjah Nahda",
    "Professional Movers and Packers Sharjah",
    "Professional Movers in Sharjah",
    "Best Moving Company in UAE",
    "Furniture Movers and Packers in Dubai",
    "House Furniture Movers in Abu Dhabi",
    "Movers and Packers Al Barsha",
    "House Movers and Packers in Abu Dhabi",
    "Affordable Movers in Dubai",
    "Best Home Movers and Packers in Dubai",
    "Movers and Packers in Marina Dubai",
    "Movers and Packers in Sharjah Al Nahda",
    "Home Shifting Services in Dubai",
    "Home Shifting Services in Sharjah",
    "Movers and Packers Dubai Silicon Oasis",
    "Professional Packers and Movers Dubai",
    "Movers Packers in Abu Dhabi",
    "Movers and Packers in Dubai Silicon Oasis",
    "Affordable Movers Dubai Moving Company",
    "Abu Dhabi Movers and Packer",
    "Best Furniture Movers and Packers in Dubai",
    "Best Furniture Movers in Abu Dhabi",
    "Best Home Movers and Packers in Sharjah",
    "Best Home Movers in Sharjah",
    "Best House Movers in Dubai",
    "Best Local Movers in Dubai",
    "Best Movers and Packers in Ajman",
    "Best Movers and Packers in Al Ain",
    "Best Movers in Al Ain",
    "Best Movers in Bur Dubai",
    "Best Movers in Dubai Marina",
    "Best Movers Packers Dubai",
    "Best Office Movers in Dubai",
    "Cheap and Best Movers in Dubai",
    "Cheap Movers and Packers in Dubai Marina",
    "Cheap Movers and Packers in Sharjah",
    "Fast House Movers and Packers Dubai",
    "Fast Movers and Packers in Dubai",
    "Furniture Movers and Packers Dubai",
    "Furniture Moving Company in Dubai",
    "Professional House Movers and Packers in Dubai",
    "No 1 UAE Mover Packers",
    "Low Price UAE Mover Packers",
    "Professional Packers and Movers Abu Dhabi",
    "Professional Packers and Movers in Dubai",
    "Residential Movers in Dubai",
    "Room Shifting Services in Abu Dhabi",
    "Villa Movers Abu Dhabi",
    "Villa Movers and Packers in Abu Dhabi",
    "Villa Movers and Packers in Sharjah",
    "Villa Movers in Al Ain",
    "Villa Movers in Palm Jumeirah",
    "Villa Movers in Sharjah"
]

export const ServicesLocations = [
  {
    title: "Movers in Abu Dhabi",
    desc: "Professional movers in Abu Dhabi offering reliable and affordable moving services for homes and offices across the UAE.",
    link: "movers-in-abu-dhabi",
  },
  {
    title: "Movers in Dubai",
    desc: "Expert movers in Dubai providing fast, secure, and cost-effective moving solutions for residential and commercial clients.",
    link: "movers-in-dubai",
  },
  {
    title: "Movers in Fujairah",
    desc: "Professional moving and packing services in Fujairah for residential, commercial, and furniture relocation across the UAE.",
    link: "movers-and-packers-in-fujairah",
  },
  {
    title: "Movers in Sharjah",
    desc: "Trusted movers and packers in Sharjah with same-day service, safe packing, and expert handling for all types of moves.",
    link: "movers-and-packers-in-sharjah",
  },
  {
    title: "Movers in Al Ain",
    desc: "Top-rated movers and packers in Al Ain specializing in villa, apartment, and office moving services at competitive rates.",
    link: "movers-and-packers-in-al-ain",
  },
  {
    title: "Movers Palm Jumeirah",
    desc: "Experienced movers and packers in Palm Jumeirah offering luxury relocation services with full packing and transport support.",
    link: "movers-and-packers-palm-jumeirah",
  },
  {
    title: "Movers in JVC",
    desc: "Affordable and professional movers in JVC (Jumeirah Village Circle) for fast, secure, and hassle-free moving solutions.",
    link: "movers-and-packers-in-jvc",
  },
  {
    title: "Movers in Business Bay",
    desc: "Efficient movers and packers in Business Bay for office relocations and home shifting with expert packing and delivery.",
    link: "movers-and-packers-in-business-bay",
  },
  {
    title: "Movers and Packers in JLT",
    desc: "Safe and reliable movers and packers in JLT (Jumeirah Lake Towers) with professional service and timely delivery.",
    link: "movers-and-packers-in-jlt",
  },
  {
    title: "Movers in Al Nahda",
    desc: "Local movers in Al Nahda offering expert house and apartment shifting services with careful packing and handling.",
    link: "movers-and-packers-in-al-nahda",
  },
  {
    title: "Movers in Al Barsha",
    desc: "Skilled movers in Al Barsha providing packing, dismantling, and transport services for all residential and commercial moves.",
    link: "movers-and-packers-in-al-barsha",
  },
  {
    title: "Movers in Arabian Ranches",
    desc: "Professional villa movers in Arabian Ranches offering stress-free moving experiences with premium packing and relocation.",
    link: "movers-and-packers-in-arabian-ranches",
  },
];

export const schemaData = {
    "@context": "https://schema.org",
    "@type": "MovingCompany",
    "name": APP.name,
    "url": APP.url,
    "logo": `${APP.url}/Picture1.png`,
    "image": `${APP.url}/nice-movers-transport-trucks.jpg`,
    "description": "Nice Movers is a leading movers and packers company in the UAE, offering affordable, fast, and secure relocation services including house shifting, villa moving, office relocation, storage, and more.",
    "telephone": "+971563560017",
    "email": "nicemovers.com@gmail.com",
    "address": {
      "@type": "PostalAddress",
      "streetAddress": "2 Moatab Bin Auf St - Bu Shaghara - Hay Al Qasimiah - Sharjah",
      "addressLocality": "Sharjah",
      "addressRegion": "Sharjah",
      "postalCode": "00000",
      "addressCountry": "AE"
    },
    "openingHoursSpecification": [
      {
        "@type": "OpeningHoursSpecification",
        "dayOfWeek": [
          "Monday",
          "Tuesday",
          "Wednesday",
          "Thursday",
          "Friday",
          "Saturday"
        ],
        "opens": "08:00",
        "closes": "20:00"
      },
      {
        "@type": "OpeningHoursSpecification",
        "dayOfWeek": "Sunday",
        "opens": "10:00",
        "closes": "18:00"
      }
    ],
    "areaServed": [
      "Abu Dhabi",
      "Dubai",
      "Fujairah",
      "Sharjah",
      "Al Ain",
      "Palm Jumeirah",
      "JVC",
      "Business Bay",
      "JLT",
      "Al Nahda",
      "Al Barsha",
      "Arabian Ranches"
    ],
    "priceRange": "$$",
    "hasOfferCatalog": {
      "@type": "OfferCatalog",
      "name": "Moving Services",
      "itemListElement": servicesList.map(services => ({
        
          "@type": "Offer",
          "itemOffered": {
            "@type": "Service",
            "name": services.title,
            "description": services.desc,
            "url": `${APP.url}/${services.link}`,
        },
      }))
    }
  };
