export const services = [
    "Dubai movers",
    "Best Mover Dubai",
    "Movers and Packers Dubai",
    "Moving Company Dubai",
    "Furniture Movers in Dubai",
    "Cheap Movers in Dubai",
    "Relocation Company in Dubai",
    "Same Day Furniture Removal",
    "Moving Company Dubai Prices",
    "Villa Movers in Dubai",
    "Cheap Moving Company Dubai",
    "Best Movers Packers Dubai",
    "Movers and Packers near me",
    "House shifting services",
    "UAE Mover Packers",
    "Mover and Packer in UAE",
    "Packers and Movers Near Me",
    "Residential Movers Near Me",
    "Movers and Packers Sharjah",
    "Furniture Movers in Dubai",
    "Cheap Movers and Packers in Dubai",
    "Best Moving Companies in Dubai",
    "Best Movers and Packers Dubai",
    "Local Movers in Dubai",
    "Office Movers in Dubai",
    "Movers and Packers Ajman",
    "Furniture Movers Abu Dhabi",
    "Cheap Movers and Packers in Abu Dhabi",
    "Best Moving Company in Abu Dhabi",
    "Professional Movers and Packers Dubai",
    "House Movers Abu Dhabi",
    "UAE Movers and Packers",
    "Best Movers in Abu Dhabi",
    "House Shifting Services Dubai",
    "Cheap Movers in Abu Dhabi",
    "Villa Movers and Packers in Dubai",
    "Villa Movers in Abu Dhabi",
    "Movers and Packers Al Ain",
    "Furniture Movers and Packers in Abu Dhabi",
    "Movers and Packers Dubai Marina",
    "Movers and Packers Al Quoz",
    "Office Movers and Packers in Dubai",
    "Best Movers and Packers in Abu Dhabi",
    "Office Movers in Abu Dhabi",
    "Movers and Packers in Dubai Marina",
    "Movers in Dubai Marina",
    "Packers and Movers Ajman",
    "Best Movers in Sharjah",
    "Abu Dhabi House Movers and Packers",
    "Expert Movers and Packers Dubai",
    "Movers and Packers Al Nahda Dubai",
    "Movers and Packers in Palm Jumeirah",
    "Movers and Packers in Mussafah",
    "Home Shifting Services in Abu Dhabi",
    "Best Movers and Packers in Sharjah",
    "Movers and Packers Bur Dubai",
    "Cheap and Best Movers and Packers in Dubai",
    "Movers in Al Nahda Dubai",
    "Movers and Packers Umm Al Quwain",
    "Movers and Packers Fujairah",
    "House Moving Companies in Abu Dhabi",
    "House Shifting Services in Sharjah",
    "Ajman Movers and Packers",
    "House Shifting Services in Abu Dhabi",
    "Office Movers in Ajman",
    "Best Furniture Movers in Dubai",
    "House Movers and Packers in Dubai",
    "Home Movers in Ajman",
    "Packers and Movers in Mussafah",
    "Home Shifting in Dubai",
    "Movers and Packers Sharjah Nahda",
    "Professional Movers and Packers Sharjah",
    "Professional Movers in Sharjah",
    "Best Moving Company in UAE",
    "Furniture Movers and Packers in Dubai",
    "House Furniture Movers in Abu Dhabi",
    "Movers and Packers Al Barsha",
    "House Movers and Packers in Abu Dhabi",
    "Affordable Movers in Dubai",
    "Best Home Movers and Packers in Dubai",
    "Movers and Packers in Marina Dubai",
    "Movers and Packers in Sharjah Al Nahda",
    "Home Shifting Services in Dubai",
    "Home Shifting Services in Sharjah",
    "Movers and Packers Dubai Silicon Oasis",
    "Professional Packers and Movers Dubai",
    "Movers Packers in Abu Dhabi",
    "Movers and Packers in Dubai Silicon Oasis",
    "Affordable Movers Dubai Moving Company",
    "Abu Dhabi Movers and Packer",
    "Best Furniture Movers and Packers in Dubai",
    "Best Furniture Movers in Abu Dhabi",
    "Best Home Movers and Packers in Sharjah",
    "Best Home Movers in Sharjah",
    "Best House Movers in Dubai",
    "Best Local Movers in Dubai",
    "Best Movers and Packers in Ajman",
    "Best Movers and Packers in Al Ain",
    "Best Movers in Al Ain",
    "Best Movers in Bur Dubai",
    "Best Movers in Dubai Marina",
    "Best Movers Packers Dubai",
    "Best Office Movers in Dubai",
    "Cheap and Best Movers in Dubai",
    "Cheap Movers and Packers in Dubai Marina",
    "Cheap Movers and Packers in Sharjah",
    "Fast House Movers and Packers Dubai",
    "Fast Movers and Packers in Dubai",
    "Furniture Movers and Packers Dubai",
    "Furniture Moving Company in Dubai",
    "Professional House Movers and Packers in Dubai",
    "No 1 UAE Mover Packers",
    "Low Price UAE Mover Packers",
    "Professional Packers and Movers Abu Dhabi",
    "Professional Packers and Movers in Dubai",
    "Residential Movers in Dubai",
    "Room Shifting Services in Abu Dhabi",
    "Villa Movers Abu Dhabi",
    "Villa Movers and Packers in Abu Dhabi",
    "Villa Movers and Packers in Sharjah",
    "Villa Movers in Al Ain",
    "Villa Movers in Palm Jumeirah",
    "Villa Movers in Sharjah"
]