import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/main/Navbar";
import Footer from "@/components/main/Footer";
import { FixedBtns } from "@/components/main/FixedBtns";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <FixedBtns />
        <div className="gray-grd"></div>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
